name: Test1-Build-Test-Deploy-

on:
  workflow_dispatch:
    push:
        - master
    schedule:
      - cron: '0 7 * * *'
      - cron: '0 21 * * *'

jobs:
    runs-on: ubuntu-latest
    name: Test1
    needs: Build-job
    if: github.ref != 'refs/heads/production'
    steps:
      - uses: actions/checkout@v1
      - name: Install surge
        uses: actions/setup-node@v1
        with:
             node-version: 14
       - run: npm install --global mocha
       - run: npm test
